# Generated by Django 5.1.1 on 2024-09-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(verbose_name='Описание фильма'),
        ),
        migrations.AlterField(
            model_name='film',
            name='review',
            field=models.TextField(verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название фильма'),
        ),
    ]
