# Generated by Django 5.1.1 on 2024-09-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_film_description_alter_film_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='film_images/', verbose_name='Обложка фильма'),
        ),
    ]
